name: flutter_application_develop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

#メモ：環境以下の通りになってる">=2.17.5 <3.0.0"
environment:
  sdk: '3.1.5'


dependencies:
  flutter:
    sdk: flutter
  #ログインで使用
  provider: ^6.1.1

  cached_network_image: ^3.3.0

#プロフィール写真の拡大に必要
  cupertino_icons: ^1.0.2

  image: ^4.1.3

  #svgファイルを利用する
  flutter_svg: ^2.0.9
  # yamlにimportするときは、インデントも揃えないとエラーになる
  # カメラと写真を読みこむパッケージ
  image_picker: ^0.8.4+4a
  # マップ表示、緯度経度を取得するパッケージ3つ
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  geolocator: ^9.0.1

  flutter_riverpod: ^2.4.5
  shared_preferences: ^2.2.2

#アプリアイコンのためのパッケージ
  flutter_launcher_icons: ^0.13.1
#プロフィールの選択
  #image_picker: ^1.0.4
  path_provider: ^2.1.1
  image_cropper: ^4.0.1
  geocoding: ^2.1.1
  http: ^0.13.6
  flutter_image_compress: ^2.1.0
  lottie: ^2.7.0
  audioplayers: ^5.2.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #メモ：2.0.0になっている
  flutter_lints: ^3.0.0

#アプリアイコンの変更
flutter_icons:       
  android: true
  ios: true
  image_path: "assets/TriCaPic_icon.png"


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #ロゴやら画像やら何やら(多分)
  assets:
    - assets/Post.svg
    - assets/PostActive.svg
    - assets/TriCaPic_logo.png
    - assets/TriCaPicapplogo1.svg
    - assets/TriCaPic_icon.png
    - assets/TimeCapsule.PNG
    - assets/Capsule_Filling_Animation.json
    - assets/Capsule_Not_Found.json
    - assets/Capsule_Not_Found2.json
    - assets/
    #Capsule_digging.mp3



